### ISSUE TITLE
我的代理服务器是socks5协议的，似乎翻译不起来

### ISSUE THREAD

**Issue by cloudyskyy** [foyoux/pygtrans#13]
我用的是shadowsocks，查了下是socks5协议，端口是1080，所以改成了以下，
client = Translate(target='en', proxies={'socks5:': 'socks5://localhost:1080'}, domain='com')，但是连接不起来。。翻译不了，能否请教下该如何修改

**Comment by Lamcoding** [comment]
经作者大大的耐心帮助，遇到了相同的问题，并最终解决了。

首先是犯下罪恶的clash（滑稽）， 建议在开代理时不要尝试clash，这是我的问题的根源
然后就是对于翻译请求的补充，最好把要翻译的内容放在一个字符串列表里，一次翻译多个语句或文档，以免请求过于频繁被封
