### ISSUE TITLE
膜拜大佬， 但是貌似链接不上谷歌翻译

### ISSUE THREAD

**Issue by kujie0121** [foyoux/pygtrans#14]
试过了在本地开代理， 直接报错提示 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /translate_a/t?tl=zh-CN&sl=auto&ie=UTF-8&oe=UTF-8&client=at&dj=1&format=html&v=1.0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B45A90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

把代码丢到了国外的服务器上执行， 倒是没有再提示连不上谷歌翻译， 但是一直提示 client.translate('Hello, Google') 返回的是空， 猜测应该是没翻译成功？返回了null 

本来想试试API的方式，但是google 好像拒绝国内的注册， 没有中国地区，填不了信用卡信息... 领不到 KEY

**Comment by lemisky** [comment]
需要连接代理梯子，就VPN。

然后不要用 Clash，多数网友反映 Clash 导致失败。 用 v2rayN https://github.com/2dust/v2rayN

**Comment by lemisky** [comment]
试试 #13 ，肯定是可以的

**Comment by kujie0121** [comment]
> 试试 #13 ，肯定是可以的

感谢， 已经解决了代理的问题， 安装了 pip install -U requests[socks]  之后， 没有再报代理链接的问题了

本地执行，跟服务器上一样，提示  client.translate 返回的是 null ， 就取不到翻译结果

**Comment by lemisky** [comment]
1. 不要开全局代理
2. 如果是 http 代理， 无需安装 `requests[socks]`
3. 肯定是可行的，你可以先试下 连接google
    
![image](https://user-images.githubusercontent.com/35125624/143670720-14b614a8-a45e-4750-94b7-94421b8a91f0.png)

**Comment by lemisky** [comment]
4. 不要使用 clash

**Comment by lemisky** [comment]
![image](https://user-images.githubusercontent.com/35125624/143670739-5cb4dc50-88a2-41b2-a424-60aa473aedaa.png)

这是我现在的测试的

**Comment by lemisky** [comment]
如果还是搞不定，就加我微信吧： lemisky

**Comment by kujie0121** [comment]
按照您的提示，单独测试了一下，已经可以翻译了 ！（激动，哈哈，小白第一次跟大佬这么近距离的交流...）

刚刚那个，貌似找到问题了， 是因为我用了  client.translate_and_detect ， 刚刚用你这种方法单独测试的返回的 404

**Comment by lemisky** [comment]
试了下，确实如此。晚点更新下项目

**Comment by lemisky** [comment]
感谢反馈 ❤️

**Comment by Kevin-free** [comment]
> 感谢反馈 ❤️

你好，请问本地开了代理，`client = Translate(proxies={'https': 'http://localhost:xxxx'})`要怎么设置还是可以不设置呢？
