### ISSUE TITLE
返回值 反向转义

### ISSUE THREAD

**Issue by DowneyRem** [foyoux/pygtrans#21]
传入  ` ' " < > & ` 等，翻译后会被html转译
![image](https://user-images.githubusercontent.com/73387736/177897184-483f6d4d-3cde-4db2-af19-fde1ad346c4e.png)
能否将被转义的上述字符，翻译后反向转义？

**Comment by lemisky** [comment]
没有这样的支持选项

**Comment by lemisky** [comment]
你可以尝试文本模式翻译

**Comment by lemisky** [comment]
https://github.com/foyoux/pygtrans/blob/main/pygtrans/Translate.py#L23-L23

**Comment by lemisky** [comment]
或者使用python自带的库进行编码

**Comment by DowneyRem** [comment]
> 你可以尝试文本模式翻译

文本模式的确不会转码，感谢
