### ISSUE TITLE
能否加一个timeout参数

### ISSUE THREAD

**Issue by godshen** [foyoux/pygtrans#29]
如题
有时候不知道什么原因, 一个简单的句子需要翻译很久才有响应
同步等待在这里, 会影响整个代码的运行效率
自己加一些东西又显得太过复杂
所以希望可以增加超时参数, 自行配置等待多长时间算翻译失败
当然了如果不设置或者设为None之类的, 可以保持和现在一样的体验

**Comment by lemisky** [comment]
OK

**Comment by lemisky** [comment]
已添加

**Comment by godshen** [comment]
> 已添加

大佬太强了, 这执行力和coding力相当max
