### ISSUE TITLE
tts功能演示

### ISSUE THREAD

**Issue by lemisky** [foyoux/pygtrans#3]
https://user-images.githubusercontent.com/35125624/126063414-0878e439-192e-409f-a0a4-233644b3a7ae.mp4

https://user-images.githubusercontent.com/35125624/126063421-4531bbdd-9235-4765-97e8-a716dbdb36b7.mp4

https://user-images.githubusercontent.com/35125624/126063429-bc52423d-fc80-4ff0-9eb5-eced440d6740.mp4

https://user-images.githubusercontent.com/35125624/126063432-4d9f5685-7a4f-4a20-bc70-c9dea6e6348e.mp4

**Comment by HC-miss** [comment]
你好, 我刚刚测试了一下, 中文转英语(target="en")得到的mp3里面也是中文声音,  这是谷歌方面翻译的原因吗

**Comment by lemisky** [comment]
@HC-miss 我看看

**Comment by lemisky** [comment]
@HC-miss 能提供一下代码吗

**Comment by HC-miss** [comment]
`from pygtrans import Translate
client = Translate()

tts = client.tts(
    '那要这样也可以, 就是我们只保存页面上面所有展示的内容，'
    '后面如果有一些其他的细节字段，我们就暂时不去保存了，直接舍弃掉。这个从设计上也简单，'
    '那商品这个地方的逻辑反而可以变更快', target='en'
)

print(client.detect("hello"))

open('trans_en.mp3', 'wb').write(tts)`

**Comment by lemisky** [comment]
@HC-miss 你是指它的内容还是中文吗?

**Comment by lemisky** [comment]
@HC-miss 你需要先翻译, 后再调用tts

**Comment by HC-miss** [comment]
> @HC-miss 你需要先翻译, 后再调用tts

好的, 谢谢,

**Comment by lemisky** [comment]
@HC-miss 这种行为是符合预期的, 以英语口吻阅读中文也没毛病呀

**Comment by lemisky** [comment]
感谢反馈🌹

**Comment by lemisky** [comment]
@HC-miss 你可以这样操作

```python
from pygtrans import Translate

client = Translate(target='en')

text = '那要这样也可以, 就是我们只保存页面上面所有展示的内容，'
'后面如果有一些其他的细节字段，我们就暂时不去保存了，直接舍弃掉。这个从设计上也简单，'
'那商品这个地方的逻辑反而可以变更快'

trans_text = client.translate(text).translatedText

tts = client.tts(trans_text)

open('test_en.mp3', 'wb').write(tts)

```

**Comment by HC-miss** [comment]
好的, 就像你刚刚说的那样, **先进行翻译在进行tts**, 这种方式比直接进行tts的效果要好得多
