### ISSUE TITLE
Failed to establish a new connection: [WinError 10061]

### ISSUE THREAD

**Issue by Hyacinth-Sui** [foyoux/pygtrans#30]
报错："由于目标计算机积极拒绝，无法连接。"

**Comment by lemisky** [comment]
网络有问题， 这个需要梯子

**Comment by Hyacinth-Sui** [comment]
挂了梯子（全局模式）依旧不能解决😭

**Comment by Hyacinth-Sui** [comment]
网页端的谷歌翻译可以正常使用（挂了梯子后），但无法通过Python调用

**Comment by lemisky** [comment]
requests.get("https://google.com")

这个你估计也会报错,你先尝试这个正常请求

**Comment by Hyacinth-Sui** [comment]
还真是😢
代码：
from requests import get
get("https://google.com")

报错：
requests.exceptions.ProxyError: HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)'))))

**Comment by Hyacinth-Sui** [comment]
根据网上所说的方法，将urllib3模块的版本号降低到1.23，现在可以成功运行print(get("https://google.com"))，输出<Response [200]>。但依旧无法使用Translate

**Comment by lemisky** [comment]
不会吧😂

**Comment by Hyacinth-Sui** [comment]
试了好多方法也没有能起作用的，算了😥应该是我这边的问题，就凑合用有道翻译的接口吧
给您添麻烦了
