### ISSUE TITLE
翻译时，单引号有时会输出乱码

### ISSUE THREAD

**Issue by tianguang2525** [foyoux/pygtrans#33]
中文翻译成英文时，有部分单引号会输出乱码
如
I didn&#39;t choose the scarf that the woman in white had worked so hard to knit for me, which made her very angry.
It&#39;s ironic for a woman wearing a black top to look at a curly-haired man who doesn&#39;t admit it.

**Comment by lemisky** [comment]
https://github.com/foyoux/pygtrans/issues/31


参考这里
