### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wuyunyan** [foyoux/pygtrans#5]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /sorry/index?continue=https://translate.google.cn/translate_a/t%3Ftl%3Dzh-CN%26sl%3Dauto%26ie%3DUTF-8%26oe%3DUTF-8%26client%3Dat%26dj%3D1%26format%3Dhtml%26v%3D1.0&q=EgR4_emiGIDX0ogGIhAtV0NFXPYnJUjAEhewUAqCMgFy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000003660850>: Failed to establish a new connectio

**Comment by lemisky** [comment]
这应该是网络问题
